const MAX_QUANTITY_ALLOWED = 12;

const FORGOT_PASSWORD_FORM_TYPE = "forgot-password";

const MAX_COUNTER_TIME = 60;
const MAX_CODE_LENGTH = 6;

export {
  MAX_QUANTITY_ALLOWED,
  MAX_CODE_LENGTH,
  MAX_COUNTER_TIME,
  FORGOT_PASSWORD_FORM_TYPE,
};
