export const USER_ACTION_TYPES = {
  SET_CURRENT_USER: "user/SET_CURRENT_USER",
  CHECK_USER_SESSION: "user/CHECK_USER_SESSION",

  SOCIAL_AUTH_SUCCESS: "user/SOCIAL_AUTH_SUCCESS",
  SOCIAL_AUTH_FAILED: "user/SOCIAL_AUTH_FAILED",

  EMAIL_SIGN_IN_START: "user/EMAIL_SIGN_IN_START",
  SIGN_IN_SUCCESS: "user/SIGN_IN_SUCCESS",
  SIGN_IN_FAILED: "user/SIGN_IN_FAILED",

  SIGN_UP_START: "user/SIGN_UP_START",
  SIGN_UP_SUCCESS: "user/SIGN_UP_SUCCESS",
  SIGN_UP_FAILED: "user/SIGN_UP_FAILED",

  LOG_OUT_START: "user/LOG_OUT_START",
  LOG_OUT_SUCCESS: "user/LOG_OUT_SUCCESS",
  LOG_OUT_FAILED: "user/LOG_OUT_FAILED",
};
