export const CART_ACTION_TYPES = {
  ADD_TO_CART_START: "cart/ADD_TO_CART_START",
  ADD_TO_CART_SUCCESS: "cart/ADD_TO_CART_SUCCESS",
  ADD_TO_CART_FAILED: "cart/ADD_TO_CART_FAILED",

  REMOVE_FROM_CART_ACTION: "cart/REMOVE_FROM_CART_ACTION",
  CLEAR_CART_ACTION: "cart/CLEAR_CART_ACTION",
};
